[book]
authors = ["xuehao"]
language = "zh-CN"
multilingual = false
src = "src"
title = "计算机组成与系统"
description = "本书将从 C 语言开始，逐步深入到底层汇编语言，一步步带你梳理计算机底层的逻辑。"

[build]
build-dir = "reader"

[output.html]
mathjax-support = true
default-theme = "Rust"
copy-fonts = false

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0         # the depth to start folding
